name: Publish Core Library to GitHub Packages

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v0.1-beta, etc.git tag v1.0.7   git push origin v1.0.8

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Grant GITHUB_TOKEN permissions to write packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get the version from the tag
        id: get_version
        run: |
          raw_version="${GITHUB_REF#refs/tags/}"
          echo "VERSION=${raw_version#v}" >> $GITHUB_OUTPUT

      - name: Publish package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: ./gradlew :core:publish -Pversion=${{ steps.get_version.outputs.VERSION }}
